export const UPDATE_INPUT = "UPDATE_INPUT";
export const SELECT_CITY = "SELECT_CITY";
export const REQUEST_RESTAURANTS = "REQUEST_RESTAURANTS";
export const RECEIVE_RESTAURANTS = "RECEIVE_RESTAURANTS";
export const REQUEST_FAILED = "REQUEST_FAILED";
